export const SEED_HR_USERS = [
  { name: 'Sarah Mitchell', email: 'sarah.mitchell@company.com', password: 'Password123!', role: 'hr', onboardingComplete: true },
  { name: 'James Wilson', email: 'james.wilson@company.com', password: 'Password123!', role: 'hr', onboardingComplete: true },
];

export const SEED_EMPLOYEES = [
  {
    user: { name: 'Alice Chen', email: 'alice.chen@company.com', password: 'Password123!', role: 'employee' },
    profile: {
      title: 'Senior Frontend Engineer', department: 'Engineering', location: 'San Francisco, CA',
      totalYearsExperience: 7, status: 'active', workType: 'full_time',
      summary: 'Senior frontend engineer with 7 years building high-performance React applications at Stripe and Airbnb.',
      skills: [
        { name: 'React', category: 'Frontend', proficiency: 'expert', yearsOfExperience: 6 },
        { name: 'TypeScript', category: 'Frontend', proficiency: 'expert', yearsOfExperience: 5 },
        { name: 'Next.js', category: 'Frontend', proficiency: 'advanced', yearsOfExperience: 4 },
        { name: 'GraphQL', category: 'Backend', proficiency: 'advanced', yearsOfExperience: 3 },
        { name: 'Tailwind CSS', category: 'Frontend', proficiency: 'expert', yearsOfExperience: 3 },
        { name: 'Node.js', category: 'Backend', proficiency: 'intermediate', yearsOfExperience: 2 },
        { name: 'AWS', category: 'Cloud', proficiency: 'intermediate', yearsOfExperience: 2 },
        { name: 'Jest', category: 'QA', proficiency: 'advanced', yearsOfExperience: 5 },
      ],
      experience: [
        { company: 'Stripe', role: 'Senior Frontend Engineer', startDate: new Date('2021-03-01'), current: true, technologies: ['React', 'TypeScript', 'GraphQL'] },
        { company: 'Airbnb', role: 'Frontend Engineer', startDate: new Date('2018-06-01'), endDate: new Date('2021-02-28'), technologies: ['React', 'Redux'] },
      ],
      certifications: [{ name: 'AWS Solutions Architect Associate', issuer: 'Amazon Web Services', issueDate: new Date('2022-05-15') }],
      approval: { status: 'approved', autoApproved: true },
      availability: { isAvailable: false, openTo: ['promotion'], noticePeriodDays: 30 },
      tags: ['react', 'frontend', 'typescript', 'senior'],
    },
  },
  {
    user: { name: 'Bob Martinez', email: 'bob.martinez@company.com', password: 'Password123!', role: 'employee' },
    profile: {
      title: 'Full Stack Engineer', department: 'Engineering', location: 'Austin, TX',
      totalYearsExperience: 5, status: 'active', workType: 'full_time',
      summary: 'Full stack engineer specializing in scalable Node.js APIs and React frontends with AWS cloud experience.',
      skills: [
        { name: 'Node.js', category: 'Backend', proficiency: 'expert', yearsOfExperience: 5 },
        { name: 'Python', category: 'Backend', proficiency: 'advanced', yearsOfExperience: 4 },
        { name: 'React', category: 'Frontend', proficiency: 'advanced', yearsOfExperience: 4 },
        { name: 'PostgreSQL', category: 'Database', proficiency: 'expert', yearsOfExperience: 5 },
        { name: 'AWS', category: 'Cloud', proficiency: 'advanced', yearsOfExperience: 3 },
        { name: 'Docker', category: 'DevOps', proficiency: 'advanced', yearsOfExperience: 3 },
        { name: 'Redis', category: 'Database', proficiency: 'intermediate', yearsOfExperience: 2 },
      ],
      experience: [
        { company: 'Shopify', role: 'Full Stack Engineer', startDate: new Date('2022-01-01'), current: true, technologies: ['Node.js', 'React', 'PostgreSQL'] },
        { company: 'HubSpot', role: 'Backend Engineer', startDate: new Date('2019-07-01'), endDate: new Date('2021-12-31'), technologies: ['Python', 'PostgreSQL'] },
      ],
      approval: { status: 'approved', autoApproved: true },
      availability: { isAvailable: true, openTo: ['new_role', 'promotion'], noticePeriodDays: 14 },
      tags: ['fullstack', 'node', 'python', 'aws'],
    },
  },
  {
    user: { name: 'Carol Johnson', email: 'carol.johnson@company.com', password: 'Password123!', role: 'employee' },
    profile: {
      title: 'ML Engineer', department: 'AI/Data', location: 'New York, NY',
      totalYearsExperience: 6, status: 'active', workType: 'full_time',
      summary: 'Machine learning engineer with deep NLP expertise. Previously at OpenAI and Google Brain. Certified TensorFlow developer.',
      skills: [
        { name: 'Python', category: 'Backend', proficiency: 'expert', yearsOfExperience: 6 },
        { name: 'TensorFlow', category: 'AI/ML', proficiency: 'expert', yearsOfExperience: 5 },
        { name: 'PyTorch', category: 'AI/ML', proficiency: 'expert', yearsOfExperience: 4 },
        { name: 'NLP', category: 'AI/ML', proficiency: 'advanced', yearsOfExperience: 4 },
        { name: 'LLM Fine-tuning', category: 'AI/ML', proficiency: 'advanced', yearsOfExperience: 2 },
        { name: 'Kubernetes', category: 'DevOps', proficiency: 'intermediate', yearsOfExperience: 2 },
        { name: 'SQL', category: 'Database', proficiency: 'advanced', yearsOfExperience: 5 },
      ],
      experience: [
        { company: 'OpenAI', role: 'ML Engineer', startDate: new Date('2022-04-01'), current: true, technologies: ['Python', 'PyTorch'] },
        { company: 'Google', role: 'Software Engineer ML', startDate: new Date('2018-09-01'), endDate: new Date('2022-03-31'), technologies: ['TensorFlow', 'Python'] },
      ],
      certifications: [
        { name: 'TensorFlow Developer Certificate', issuer: 'Google', issueDate: new Date('2020-03-01') },
        { name: 'Deep Learning Specialization', issuer: 'DeepLearning.AI', issueDate: new Date('2019-06-01') },
      ],
      approval: { status: 'approved', autoApproved: true },
      availability: { isAvailable: false, openTo: ['advisory'], noticePeriodDays: 60 },
      tags: ['ml', 'nlp', 'python', 'llm', 'senior'],
    },
  },
  {
    user: { name: 'David Park', email: 'david.park@company.com', password: 'Password123!', role: 'employee' },
    profile: {
      title: 'Senior DevOps Engineer', department: 'Infrastructure', location: 'Seattle, WA',
      totalYearsExperience: 8, status: 'active', workType: 'full_time',
      summary: 'Senior DevOps engineer with 8 years managing cloud-native infrastructure at Netflix and Amazon. CKA and AWS Pro certified.',
      skills: [
        { name: 'Kubernetes', category: 'DevOps', proficiency: 'expert', yearsOfExperience: 5 },
        { name: 'Docker', category: 'DevOps', proficiency: 'expert', yearsOfExperience: 7 },
        { name: 'Terraform', category: 'DevOps', proficiency: 'expert', yearsOfExperience: 5 },
        { name: 'AWS', category: 'Cloud', proficiency: 'expert', yearsOfExperience: 8 },
        { name: 'CI/CD', category: 'DevOps', proficiency: 'expert', yearsOfExperience: 7 },
        { name: 'Python', category: 'Backend', proficiency: 'advanced', yearsOfExperience: 5 },
        { name: 'Go', category: 'Backend', proficiency: 'intermediate', yearsOfExperience: 2 },
        { name: 'Prometheus', category: 'DevOps', proficiency: 'advanced', yearsOfExperience: 4 },
      ],
      experience: [
        { company: 'Netflix', role: 'Senior DevOps Engineer', startDate: new Date('2020-08-01'), current: true, technologies: ['Kubernetes', 'AWS', 'Terraform'] },
        { company: 'Amazon', role: 'Cloud Infrastructure Engineer', startDate: new Date('2015-06-01'), endDate: new Date('2020-07-31'), technologies: ['AWS', 'Docker', 'Python'] },
      ],
      certifications: [
        { name: 'AWS Solutions Architect Professional', issuer: 'Amazon Web Services', issueDate: new Date('2021-02-01') },
        { name: 'Certified Kubernetes Administrator', issuer: 'CNCF', issueDate: new Date('2021-08-01') },
      ],
      approval: { status: 'approved', autoApproved: true },
      availability: { isAvailable: true, openTo: ['new_role', 'promotion'], noticePeriodDays: 30 },
      tags: ['devops', 'kubernetes', 'aws', 'terraform', 'senior'],
    },
  },
  {
    user: { name: 'Emma Wilson', email: 'emma.wilson@company.com', password: 'Password123!', role: 'employee' },
    profile: {
      title: 'Lead Product Designer', department: 'Design', location: 'London, UK',
      totalYearsExperience: 6, status: 'active', workType: 'full_time',
      summary: 'Lead product designer creating intuitive experiences for complex enterprise software. Expert in design systems and user research.',
      skills: [
        { name: 'Figma', category: 'Design', proficiency: 'expert', yearsOfExperience: 5 },
        { name: 'UX Research', category: 'Design', proficiency: 'expert', yearsOfExperience: 6 },
        { name: 'Prototyping', category: 'Design', proficiency: 'expert', yearsOfExperience: 6 },
        { name: 'CSS', category: 'Frontend', proficiency: 'advanced', yearsOfExperience: 5 },
        { name: 'Design Systems', category: 'Design', proficiency: 'expert', yearsOfExperience: 4 },
        { name: 'React', category: 'Frontend', proficiency: 'intermediate', yearsOfExperience: 2 },
        { name: 'Motion Design', category: 'Design', proficiency: 'advanced', yearsOfExperience: 3 },
      ],
      experience: [
        { company: 'Linear', role: 'Lead Product Designer', startDate: new Date('2021-05-01'), current: true, technologies: ['Figma', 'React'] },
        { company: 'Intercom', role: 'Product Designer', startDate: new Date('2018-02-01'), endDate: new Date('2021-04-30'), technologies: ['Figma', 'CSS'] },
      ],
      approval: { status: 'approved', autoApproved: true },
      availability: { isAvailable: true, openTo: ['new_role', 'lateral_transfer'], noticePeriodDays: 28 },
      tags: ['design', 'ux', 'figma', 'design-systems', 'senior'],
    },
  },
  {
    user: { name: 'Frank Thomas', email: 'frank.thomas@company.com', password: 'Password123!', role: 'employee' },
    profile: {
      title: 'Senior Backend Engineer', department: 'Engineering', location: 'Chicago, IL',
      totalYearsExperience: 10, status: 'active', workType: 'full_time',
      summary: 'Experienced backend engineer with 10 years in Java and distributed systems. Strong background in financial technology.',
      skills: [
        { name: 'Java', category: 'Backend', proficiency: 'expert', yearsOfExperience: 10 },
        { name: 'Spring Boot', category: 'Backend', proficiency: 'expert', yearsOfExperience: 8 },
        { name: 'PostgreSQL', category: 'Database', proficiency: 'expert', yearsOfExperience: 9 },
        { name: 'Microservices', category: 'Backend', proficiency: 'expert', yearsOfExperience: 6 },
        { name: 'Kafka', category: 'Backend', proficiency: 'advanced', yearsOfExperience: 4 },
        { name: 'AWS', category: 'Cloud', proficiency: 'advanced', yearsOfExperience: 5 },
        { name: 'Kotlin', category: 'Backend', proficiency: 'intermediate', yearsOfExperience: 2 },
      ],
      experience: [
        { company: 'JPMorgan Chase', role: 'Senior Backend Engineer', startDate: new Date('2019-01-01'), current: true, technologies: ['Java', 'Spring Boot', 'Kafka'] },
        { company: 'IBM', role: 'Software Engineer', startDate: new Date('2014-06-01'), endDate: new Date('2018-12-31'), technologies: ['Java', 'PostgreSQL'] },
      ],
      approval: { status: 'approved', autoApproved: true },
      availability: { isAvailable: false, openTo: ['promotion'], noticePeriodDays: 60 },
      tags: ['java', 'backend', 'microservices', 'fintech', 'senior'],
    },
  },
  {
    user: { name: 'Grace Lee', email: 'grace.lee@company.com', password: 'Password123!', role: 'employee' },
    profile: {
      title: 'Mobile Engineer', department: 'Engineering', location: 'Los Angeles, CA',
      totalYearsExperience: 4, status: 'active', workType: 'full_time',
      summary: 'Mobile engineer building consumer-facing apps with millions of users. Strong in React Native and native iOS Swift.',
      skills: [
        { name: 'React Native', category: 'Mobile', proficiency: 'expert', yearsOfExperience: 4 },
        { name: 'Swift', category: 'Mobile', proficiency: 'advanced', yearsOfExperience: 3 },
        { name: 'TypeScript', category: 'Frontend', proficiency: 'advanced', yearsOfExperience: 3 },
        { name: 'iOS', category: 'Mobile', proficiency: 'advanced', yearsOfExperience: 3 },
        { name: 'Firebase', category: 'Backend', proficiency: 'advanced', yearsOfExperience: 3 },
        { name: 'GraphQL', category: 'Backend', proficiency: 'intermediate', yearsOfExperience: 2 },
      ],
      experience: [
        { company: 'Duolingo', role: 'Mobile Engineer', startDate: new Date('2022-06-01'), current: true, technologies: ['React Native', 'Swift'] },
        { company: 'Uber', role: 'Mobile Engineer', startDate: new Date('2020-09-01'), endDate: new Date('2022-05-31'), technologies: ['React Native', 'TypeScript'] },
      ],
      approval: { status: 'approved', autoApproved: true },
      availability: { isAvailable: true, openTo: ['new_role', 'promotion'], noticePeriodDays: 14 },
      tags: ['mobile', 'react-native', 'swift', 'ios', 'mid-level'],
    },
  },
  {
    user: { name: 'Henry Brown', email: 'henry.brown@company.com', password: 'Password123!', role: 'employee' },
    profile: {
      title: 'Principal Cloud Architect', department: 'Infrastructure', location: 'Denver, CO',
      totalYearsExperience: 12, status: 'active', workType: 'full_time',
      summary: 'Multi-cloud architect with 12 years designing enterprise cloud solutions. Triple-certified across AWS, Azure, and GCP.',
      skills: [
        { name: 'AWS', category: 'Cloud', proficiency: 'expert', yearsOfExperience: 12 },
        { name: 'Azure', category: 'Cloud', proficiency: 'expert', yearsOfExperience: 8 },
        { name: 'GCP', category: 'Cloud', proficiency: 'advanced', yearsOfExperience: 5 },
        { name: 'Terraform', category: 'DevOps', proficiency: 'expert', yearsOfExperience: 7 },
        { name: 'Security', category: 'Security', proficiency: 'advanced', yearsOfExperience: 8 },
        { name: 'Python', category: 'Backend', proficiency: 'advanced', yearsOfExperience: 6 },
        { name: 'Architecture Design', category: 'Management', proficiency: 'expert', yearsOfExperience: 8 },
      ],
      experience: [
        { company: 'Microsoft', role: 'Principal Cloud Architect', startDate: new Date('2018-03-01'), current: true, technologies: ['Azure', 'AWS', 'Terraform'] },
        { company: 'Accenture', role: 'Cloud Solutions Architect', startDate: new Date('2012-09-01'), endDate: new Date('2018-02-28'), technologies: ['AWS', 'GCP'] },
      ],
      certifications: [
        { name: 'AWS Solutions Architect Professional', issuer: 'Amazon Web Services', issueDate: new Date('2020-01-01') },
        { name: 'Azure Solutions Architect Expert', issuer: 'Microsoft', issueDate: new Date('2020-06-01') },
        { name: 'Google Professional Cloud Architect', issuer: 'Google', issueDate: new Date('2021-03-01') },
      ],
      approval: { status: 'approved', autoApproved: true },
      availability: { isAvailable: false, openTo: ['advisory'], noticePeriodDays: 90 },
      tags: ['cloud', 'aws', 'azure', 'gcp', 'architect', 'principal'],
    },
  },
  {
    user: { name: 'Priya Sharma', email: 'priya.sharma@company.com', password: 'Password123!', role: 'employee' },
    profile: {
      title: 'Senior Data Engineer', department: 'Data Science', location: 'Toronto, Canada',
      totalYearsExperience: 6, status: 'active', workType: 'full_time',
      summary: 'Senior data engineer building petabyte-scale data platforms at Snowflake and Databricks. Expert in real-time streaming pipelines and data warehousing.',
      skills: [
        { name: 'Apache Spark', category: 'Data', proficiency: 'expert', yearsOfExperience: 5 },
        { name: 'Python', category: 'Backend', proficiency: 'expert', yearsOfExperience: 6 },
        { name: 'SQL', category: 'Database', proficiency: 'expert', yearsOfExperience: 6 },
        { name: 'Snowflake', category: 'Data', proficiency: 'expert', yearsOfExperience: 4 },
        { name: 'Apache Kafka', category: 'Data', proficiency: 'advanced', yearsOfExperience: 3 },
        { name: 'dbt', category: 'Data', proficiency: 'advanced', yearsOfExperience: 3 },
        { name: 'AWS', category: 'Cloud', proficiency: 'advanced', yearsOfExperience: 4 },
        { name: 'Airflow', category: 'Data', proficiency: 'advanced', yearsOfExperience: 4 },
      ],
      experience: [
        { company: 'Snowflake', role: 'Senior Data Engineer', startDate: new Date('2021-09-01'), current: true, technologies: ['Spark', 'Snowflake', 'Kafka'] },
        { company: 'Databricks', role: 'Data Engineer', startDate: new Date('2018-07-01'), endDate: new Date('2021-08-31'), technologies: ['Spark', 'Python', 'SQL'] },
      ],
      certifications: [
        { name: 'Databricks Certified Associate Developer for Apache Spark', issuer: 'Databricks', issueDate: new Date('2020-08-01') },
        { name: 'dbt Certified Developer', issuer: 'dbt Labs', issueDate: new Date('2022-11-01') },
      ],
      approval: { status: 'approved', autoApproved: true },
      availability: { isAvailable: true, openTo: ['new_role', 'promotion'], noticePeriodDays: 21 },
      tags: ['data', 'spark', 'snowflake', 'kafka', 'pipeline', 'senior'],
    },
  },
  {
    user: { name: 'Marcus Reed', email: 'marcus.reed@company.com', password: 'Password123!', role: 'employee' },
    profile: {
      title: 'Application Security Engineer', department: 'Engineering', location: 'Austin, TX',
      totalYearsExperience: 7, status: 'active', workType: 'full_time',
      summary: 'Application security engineer with expertise in penetration testing, secure code review, and threat modeling. OSCP and CEH certified. Built security programs from scratch at two fintech unicorns.',
      skills: [
        { name: 'Penetration Testing', category: 'Security', proficiency: 'expert', yearsOfExperience: 6 },
        { name: 'OWASP', category: 'Security', proficiency: 'expert', yearsOfExperience: 7 },
        { name: 'Python', category: 'Backend', proficiency: 'advanced', yearsOfExperience: 5 },
        { name: 'Burp Suite', category: 'Security', proficiency: 'expert', yearsOfExperience: 6 },
        { name: 'Threat Modeling', category: 'Security', proficiency: 'advanced', yearsOfExperience: 5 },
        { name: 'AWS Security', category: 'Security', proficiency: 'advanced', yearsOfExperience: 4 },
        { name: 'Docker', category: 'DevOps', proficiency: 'intermediate', yearsOfExperience: 3 },
      ],
      experience: [
        { company: 'Brex', role: 'Senior Application Security Engineer', startDate: new Date('2021-04-01'), current: true, technologies: ['Python', 'Burp Suite', 'AWS'] },
        { company: 'Robinhood', role: 'Security Engineer', startDate: new Date('2017-08-01'), endDate: new Date('2021-03-31'), technologies: ['Python', 'OWASP'] },
      ],
      certifications: [
        { name: 'Offensive Security Certified Professional (OSCP)', issuer: 'Offensive Security', issueDate: new Date('2019-04-01') },
        { name: 'Certified Ethical Hacker (CEH)', issuer: 'EC-Council', issueDate: new Date('2018-01-01') },
      ],
      approval: { status: 'approved', autoApproved: true },
      availability: { isAvailable: true, openTo: ['new_role', 'lateral_transfer'], noticePeriodDays: 30 },
      tags: ['security', 'appsec', 'pentest', 'owasp', 'fintech'],
    },
  },
  {
    user: { name: 'Sofia Rossi', email: 'sofia.rossi@company.com', password: 'Password123!', role: 'employee' },
    profile: {
      title: 'Senior Product Manager', department: 'Product', location: 'New York, NY',
      totalYearsExperience: 8, status: 'active', workType: 'full_time',
      summary: 'Senior PM with 8 years shipping 0-to-1 products in B2B SaaS and marketplace platforms. Expert at translating ambiguous problems into clear product roadmaps using data-driven frameworks.',
      skills: [
        { name: 'Product Strategy', category: 'Management', proficiency: 'expert', yearsOfExperience: 8 },
        { name: 'Roadmap Planning', category: 'Management', proficiency: 'expert', yearsOfExperience: 7 },
        { name: 'SQL', category: 'Database', proficiency: 'advanced', yearsOfExperience: 6 },
        { name: 'A/B Testing', category: 'Data', proficiency: 'expert', yearsOfExperience: 6 },
        { name: 'Figma', category: 'Design', proficiency: 'intermediate', yearsOfExperience: 4 },
        { name: 'Agile / Scrum', category: 'Management', proficiency: 'expert', yearsOfExperience: 8 },
        { name: 'User Research', category: 'Design', proficiency: 'advanced', yearsOfExperience: 6 },
      ],
      experience: [
        { company: 'Notion', role: 'Senior Product Manager', startDate: new Date('2020-11-01'), current: true },
        { company: 'Atlassian', role: 'Product Manager', startDate: new Date('2016-05-01'), endDate: new Date('2020-10-31') },
      ],
      certifications: [
        { name: 'Certified Scrum Product Owner (CSPO)', issuer: 'Scrum Alliance', issueDate: new Date('2017-09-01') },
      ],
      approval: { status: 'approved', autoApproved: true },
      availability: { isAvailable: false, openTo: ['promotion', 'advisory'], noticePeriodDays: 45 },
      tags: ['product', 'strategy', 'saas', 'agile', 'senior'],
    },
  },
  {
    user: { name: 'Liam O\'Brien', email: 'liam.obrien@company.com', password: 'Password123!', role: 'employee' },
    profile: {
      title: 'Staff QA Engineer / SDET', department: 'QA', location: 'Dublin, Ireland',
      totalYearsExperience: 9, status: 'active', workType: 'full_time',
      summary: 'Staff SDET with 9 years building automation frameworks from scratch. Led QA strategy across 15-engineer teams at Workday and ServiceNow. Expert in API and performance testing.',
      skills: [
        { name: 'Selenium', category: 'QA', proficiency: 'expert', yearsOfExperience: 8 },
        { name: 'Cypress', category: 'QA', proficiency: 'expert', yearsOfExperience: 5 },
        { name: 'Playwright', category: 'QA', proficiency: 'advanced', yearsOfExperience: 3 },
        { name: 'Java', category: 'Backend', proficiency: 'advanced', yearsOfExperience: 7 },
        { name: 'Python', category: 'Backend', proficiency: 'advanced', yearsOfExperience: 5 },
        { name: 'k6', category: 'QA', proficiency: 'advanced', yearsOfExperience: 3 },
        { name: 'CI/CD', category: 'DevOps', proficiency: 'advanced', yearsOfExperience: 6 },
        { name: 'API Testing', category: 'QA', proficiency: 'expert', yearsOfExperience: 9 },
      ],
      experience: [
        { company: 'Workday', role: 'Staff QA Engineer', startDate: new Date('2020-01-01'), current: true, technologies: ['Selenium', 'Java', 'Cypress'] },
        { company: 'ServiceNow', role: 'Senior SDET', startDate: new Date('2015-03-01'), endDate: new Date('2019-12-31'), technologies: ['Python', 'Selenium', 'API Testing'] },
      ],
      certifications: [
        { name: 'ISTQB Advanced Test Automation Engineer', issuer: 'ISTQB', issueDate: new Date('2018-05-01') },
      ],
      approval: { status: 'approved', autoApproved: true },
      availability: { isAvailable: true, openTo: ['new_role', 'promotion'], noticePeriodDays: 30 },
      tags: ['qa', 'sdet', 'automation', 'cypress', 'selenium', 'staff'],
    },
  },
  {
    user: { name: 'Zara Ahmed', email: 'zara.ahmed@company.com', password: 'Password123!', role: 'employee' },
    profile: {
      title: 'Backend Engineer – Golang', department: 'Engineering', location: 'Singapore',
      totalYearsExperience: 5, status: 'active', workType: 'full_time',
      summary: 'Backend engineer specializing in high-throughput Go microservices. Designed payment infrastructure handling 50K TPS at Grab. Strong in distributed systems and gRPC.',
      skills: [
        { name: 'Go', category: 'Backend', proficiency: 'expert', yearsOfExperience: 5 },
        { name: 'gRPC', category: 'Backend', proficiency: 'expert', yearsOfExperience: 4 },
        { name: 'Microservices', category: 'Backend', proficiency: 'expert', yearsOfExperience: 5 },
        { name: 'PostgreSQL', category: 'Database', proficiency: 'advanced', yearsOfExperience: 4 },
        { name: 'Redis', category: 'Database', proficiency: 'advanced', yearsOfExperience: 4 },
        { name: 'Kubernetes', category: 'DevOps', proficiency: 'advanced', yearsOfExperience: 3 },
        { name: 'Kafka', category: 'Backend', proficiency: 'advanced', yearsOfExperience: 3 },
        { name: 'Python', category: 'Backend', proficiency: 'intermediate', yearsOfExperience: 2 },
      ],
      experience: [
        { company: 'Grab', role: 'Backend Engineer', startDate: new Date('2021-02-01'), current: true, technologies: ['Go', 'gRPC', 'Kafka', 'Kubernetes'] },
        { company: 'Sea Group', role: 'Software Engineer', startDate: new Date('2019-07-01'), endDate: new Date('2021-01-31'), technologies: ['Go', 'PostgreSQL', 'Redis'] },
      ],
      certifications: [
        { name: 'Certified Kubernetes Application Developer (CKAD)', issuer: 'CNCF', issueDate: new Date('2022-04-01') },
      ],
      approval: { status: 'approved', autoApproved: true },
      availability: { isAvailable: true, openTo: ['new_role', 'promotion', 'relocation'], noticePeriodDays: 21 },
      tags: ['go', 'golang', 'microservices', 'grpc', 'backend', 'payments'],
    },
  },
];
